export const sites = [
    {
      site: "Edgewood Acres",
      address: "439 Church Rd",
      city: "Sicklerville",
      zip: "08081",
      phone: "856-7888888",
      county: "Camden",
      id: "edgewoodAcres",
      href: "/about/#edge_a",
    },
    {
      site: "Edgewood Gardens",
      address: "439 Church Rd",
      city: "Sicklerville",
      zip: "08081",
      phone: "856-788-8888",
      county: "Camden",
      id: "edgewoodGardens",
      href: "#edge_g",
    },
    {
      site: "Hayes Mill I",
      address: "187 Hayes Mill Road",
      city: "Atco",
      zip: "08084",
      phone: "",
      county: "Camden",
      id: "hayesI",
      href: "#hayes_i",
    },
    {
      site: "Hayes Mill II",
      address: "207 Hayes Mill Road",
      city: "Atco",
      zip: "08084",
      phone: "",
      county: "Camden",
      id: "hayesII"

    },
    {
      site: "Hillcrest",
      address: "160 West Avenue",
      city: "Woodstown",
      zip: "08098",
      phone: "",
      county: "Salem",
    },
    {
      site: "Hillcrest West",
      address: "619 Soders Road",
      city: "Carneys Point",
      zip: "08069",
      phone: "",
      county: "Salem",
    },
    {
      site: "Buena Terrace",
      address: "1002 W Summer Ave",
      city: "Minotola",
      zip: "08341",
      phone: "",
      county: "Atlantic",
    },
    {
      site: "Kingsway Apts",
      address: "1 Lore Drive",
      city: "Swedesboro",
      zip: "08085",
      phone: "",
      county: "Gloucester",
    },
  
    {
      site: "Barclay Village",
      address: "Lake St",
      city: "Jamesburg",
      zip: "08831",
      phone: "",
      county: "Middlesex",
    },
    {
      site: "Cherry Court",
      address: "Cherry Street",
      city: "Jamesburg",
      zip: "08831",
      phone: "",
      county: "Middlesex",
    },
    {
      site: "Monroe Towne",
      address: "800 N Main Street",
      city: "Williamstown",
      zip: "08094",
      phone: "",
      county: "Gloucester",
    },
    {
      site: "Monroe Towne East",
      address: "175 Walnut Street",
      city: "Williamstown",
      zip: "08094",
      phone: "",
      county: "Gloucester",
    },
    {
      site: "Liverpool",
      address: "733 Philadelphia Ave",
      city: "Egg Harbor",
      zip: "08215",
      phone: "",
      county: "Atlantic",
    },
    {
      site: "Aloe Village",
      address: "1311 Aloe Road",
      city: "Egg Harbor",
      zip: "08215",
      phone: "",
      county: "Atlantic",
    },
    {
      site: "Delseaview",
      address: "15 Costill Ave",
      city: "Clayton",
      zip: "08312",
      phone: "",
      county: "Gloucester",
    },
    {
      site: "Royal Oaks",
      address: "259 Pine Brook Drive",
      city: "Mantua",
      zip: "08051",
      phone: "",
      county: "Gloucester",
    },
    {
      site: "Liverpool South",
      address: "",
      city: "Port Norris",
      zip: "08349",
      phone: "",
      county: "Cumberland",
      id: "",
      href: "/about/#hayes_i",
    },
  ];
  